# Generated by Django 4.0.4 on 2022-08-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamRed_score', models.IntegerField()),
                ('teamBlue_score', models.IntegerField()),
                ('teamRed_players', models.CharField(max_length=200)),
                ('teamBlue_players', models.CharField(max_length=200)),
                ('teamRed_indexPlayerGoalsandAssist', models.CharField(max_length=200)),
                ('teamBlue_indexPlayerGoalsandAssist', models.CharField(max_length=200)),
                ('game_Date', models.DateField(verbose_name='date Played')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('player_lifeTimeGoals', models.IntegerField()),
                ('player_lifeTimeAssists', models.IntegerField()),
                ('player_lifeTimeScore', models.IntegerField()),
            ],
        ),
    ]
