# Generated by Django 4.0.4 on 2022-08-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teamBlue_players',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='teamRed_players',
            field=models.JSONField(),
        ),
    ]
