# Generated by Django 4.0.4 on 2022-08-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_game_teamblue_indexplayergoalsandassist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_Complete',
            field=models.BooleanField(default=False),
        ),
    ]
