# Generated by Django 4.0.4 on 2022-08-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_game_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
